name: "Get access token for AEM"
description: "Get access token for AEM"
author: "Experience Catalyst"
inputs:
  operation:
    description: "The operation to perform."
    required: true
  credentials_path:
    description: "The decoded credentials in a JSON string."
  urls:
    description: "The relative page url paths to preview or publish."
  context:
    description: "The AEMY context."
outputs:
  access_token:
    description: "The access token for AEM"
runs:
  using: 'node20'
  main: 'sta-aem-helper.js'
